name: Deploy Angular to Nginx

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (prod)
        run: |
          npx ng build --configuration production
          echo "Built dist content:"
          ls -la dist

      - name: Copy files via rsync over SSH
        uses: burnett01/rsync-deployments@v7.0.2
        with:
          switches: -avzr --delete
          path: dist/frontend/browser/
          remote_path: ${{ secrets.TARGET_DIR }}/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo nginx -t && sudo systemctl reload nginx
