name: Deploy Angular to Nginx

on:
  push:
    branches: [ "master" ]   # troque para "main" se for sua branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Probe SSH (checa conexão e permissões)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            whoami
            hostname
            sudo mkdir -p ${{ secrets.TARGET_DIR }}
            sudo chown -R ${{ secrets.SSH_USER }}:www-data /var/www/cafeselivros
            sudo chmod 755 /var/www /var/www/cafeselivros
            date | tee ${{ secrets.TARGET_DIR }}/_probe.txt
            ls -la ${{ secrets.TARGET_DIR }} | head

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (prod)
        run: |
          npx ng build --configuration production
          echo "dist tree:" && ls -la dist
          echo "browser tree:" && ls -la dist/frontend/browser | head -n 100

      - name: Copy files via rsync over SSH
        uses: burnett01/rsync-deployments@v7.0.2
        with:
          switches: -avzr --delete
          path: dist/frontend/browser/
          remote_path: ${{ secrets.TARGET_DIR }}/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            test -f ${{ secrets.TARGET_DIR }}/index.html
            sudo nginx -t
            sudo systemctl reload nginx
